spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: always
  profiles:
    active: ${APP_ENV:dev}
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
sentry:
  dsn: https://b728619b30a3e1b5aa0544ee9d95dec0@o4507176765227008.ingest.de.sentry.io/4507176774008912
  traces-sample-rate: 1.0