spring:
  datasource:
    url: jdbc:postgresql://dpg-coub6qq1hbls7382pqr0-a.frankfurt-postgres.render.com/seo_kd_umgn
    username: seo_kd_umgn_user
    password: Dsq1VAptW5k8zrdTZVWlPZwDgvbyIQEi
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL15Dialect