spring:
  datasource:
    username: SA
    password: password
    url: jdbc:h2:mem:spring
  h2:
    console:
      enabled: true
      path: /h2-console/
      settings:
        web-allow-others: true
logging:
  level:
    root: INFO
    web: DEBUG