spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    active: ${APP_ENV:dev}
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem