spring:
  datasource:
    url: jdbc:postgresql://dpg-cmqi5v21hbls73fk15s0-a.frankfurt-postgres.render.com/seo_kd
    username: seo_kd_user
    password: w2O2btrsEVsRo3lwZ1mtszwhOgaZceeG
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL15Dialect